part of '../session_client_stub.dart';

const ModeCatalog _scriptedModeCatalog = ModeCatalog(
  defaultMode: 'personal_assistant',
  modes: [
    ModeProfile(
      id: 'personal_assistant',
      label: 'Personal Assistant',
      defaultScope: 'global',
      capabilityClass: 'conversation',
      activeSkills: ['miku-voice', 'personal-assistant-state-capture'],
      capabilities: [
        'drive.*',
        'project.*',
        'http.request',
        'resources.read:artifact',
        'resources.read:drive',
        'resources.read:skill',
      ],
      description: 'Planning, reminders, writing, and open loops.',
    ),
    ModeProfile(
      id: 'ambiguity_grill',
      label: 'Ambiguity Grill',
      defaultScope: 'global',
      capabilityClass: 'conversation',
      activeSkills: ['miku-voice', 'ambiguity-grill'],
      capabilities: [],
      description: 'Sharp clarification before planning.',
    ),
    ModeProfile(
      id: 'negative_state_grounding',
      label: 'Negative-State Grounding',
      defaultScope: 'global',
      capabilityClass: 'conversation',
      activeSkills: ['miku-voice', 'negative-state-grounding'],
      capabilities: [],
      description: 'Stabilize overwhelm before action.',
    ),
    ModeProfile(
      id: 'serious_engineer',
      label: 'Serious Engineer',
      defaultScope: 'project:tempestmiku',
      capabilityClass: 'engineering',
      activeSkills: [],
      capabilities: [
        'fs.*',
        'code.*',
        'git.clone',
        'git.init',
        'git.add',
        'git.mv',
        'git.restore',
        'git.rm',
        'git.bisect',
        'git.grep',
        'git.show',
        'git.status',
        'git.diff',
        'git.log',
        'git.commit',
        'git.push',
        'git.pull',
        'proc.*',
        'agents.*',
        'resources.read:agent',
        'resources.read:history',
        'backend.coding',
      ],
      description:
          'Code, production, orchestration, irreversible, or external work.',
    ),
  ],
);
