-- P8 review hardening: snapshot embedding generations against a monotonic scope revision, retain
-- the newest active pointer under mixed workers, and persist per-job validation failures.

create table if not exists memory_scope_revisions(
    owner_subject text not null check (btrim(owner_subject) <> ''),
    memory_scope text not null,
    revision bigint not null default 0 check (revision >= 0),
    updated_at timestamptz not null default now(),
    primary key(owner_subject, memory_scope)
);

insert into memory_scope_revisions(owner_subject, memory_scope, revision, updated_at)
select owner_subject, memory_scope, 1, now()
  from memory_records
 group by owner_subject, memory_scope
on conflict (owner_subject, memory_scope) do nothing;

create or replace function tm_memory_bump_scope_revision()
returns trigger language plpgsql as $$
declare
    revision_owner text;
    revision_scope text;
begin
    if tg_op = 'UPDATE'
       and old.owner_subject is not distinct from new.owner_subject
       and old.memory_scope is not distinct from new.memory_scope
       and old.content_key is not distinct from new.content_key
       and old.status is not distinct from new.status
       and old.effective_to is not distinct from new.effective_to
       and old.corrects_record_id is not distinct from new.corrects_record_id
       and old.corrected_by_record_id is not distinct from new.corrected_by_record_id
       and old.supersedes_record_id is not distinct from new.supersedes_record_id
       and old.superseded_by_record_id is not distinct from new.superseded_by_record_id then
        return new;
    end if;
    revision_owner := case when tg_op = 'DELETE' then old.owner_subject else new.owner_subject end;
    revision_scope := case when tg_op = 'DELETE' then old.memory_scope else new.memory_scope end;
    insert into memory_scope_revisions(owner_subject, memory_scope, revision, updated_at)
    values (revision_owner, revision_scope, 1, now())
    on conflict (owner_subject, memory_scope) do update set
        revision = memory_scope_revisions.revision + 1,
        updated_at = excluded.updated_at;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

drop trigger if exists tm_memory_records_scope_revision on memory_records;
create trigger tm_memory_records_scope_revision
after insert or delete or update on memory_records
for each row execute function tm_memory_bump_scope_revision();

alter table memory_embedding_generations
    add column if not exists generation_order bigint generated by default as identity,
    add column if not exists snapshot_revision bigint not null default 0 check (snapshot_revision >= 0),
    add column if not exists input_limit_bytes integer not null default 16384
        check (input_limit_bytes > 0 and input_limit_bytes <= 65536);

create unique index if not exists memory_embedding_generations_order_idx
    on memory_embedding_generations(generation_order);

alter table memory_embedding_active_versions
    add column if not exists generation_order bigint not null default 0,
    add column if not exists snapshot_revision bigint not null default 0 check (snapshot_revision >= 0);

update memory_embedding_active_versions active
   set generation_order = generation.generation_order
  from memory_embedding_generations generation
 where generation.owner_subject = active.owner_subject
   and generation.memory_scope = active.memory_scope
   and generation.embedding_version = active.embedding_version;

alter table memory_embedding_jobs
    add column if not exists input_limit_bytes integer not null default 16384
        check (input_limit_bytes > 0 and input_limit_bytes <= 65536),
    add column if not exists failure_code text;

create or replace function tm_memory_reject_embedding_pointer_rollback()
returns trigger language plpgsql as $$
begin
    if tg_op = 'UPDATE' and (
        new.generation_order < old.generation_order
        or (new.generation_order = old.generation_order
            and new.snapshot_revision < old.snapshot_revision)
    ) then
        raise exception using errcode = '23514',
            message = 'memory embedding active pointer rollback is forbidden';
    end if;
    return new;
end;
$$;

drop trigger if exists tm_memory_active_versions_no_rollback
    on memory_embedding_active_versions;
create trigger tm_memory_active_versions_no_rollback
before insert or update on memory_embedding_active_versions
for each row execute function tm_memory_reject_embedding_pointer_rollback();
